---

codecov:
  require_ci_to_pass: yes
  branch: master

comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  range: 50..80
  round: down
  precision: 0
  status:
    project:
      default:
        # Set the overall project code coverage requirement to 70%
        target: 80
    patch:
      default:
        # Set the pull request requirement to not regress overall coverage by more than 5%
        # and let codecov.io set the goal for the code changed in the patch.
        target: auto
        threshold: 8

ignore:
  - cmd/**/*
  - main.go
