test:
	go test ./...

build:
	go build ./...

run:
	go run ./...

lint:
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0 && golangci-lint run

cross-compile:
	# 32-Bit Systems
	# FreeBDS
	GOOS=freebsd GOARCH=386 go build -o bin/main-freebsd-386 ./...
	# MacOS
	GOOS=darwin GOARCH=386 go build -o bin/main-darwin-386 ./...
	# Linux
	GOOS=linux GOARCH=386 go build -o bin/main-linux-386 ./...
	# Windows
	GOOS=windows GOARCH=386 go build -o bin/main-windows-386 ./...
        # 64-Bit
	# FreeBDS
	GOOS=freebsd GOARCH=amd64 go build -o bin/main-freebsd-amd64 ./...
	# MacOS
	GOOS=darwin GOARCH=amd64 go build -o bin/main-darwin-amd64 ./...
	# Linux
	GOOS=linux GOARCH=amd64 go build -o bin/main-linux-amd64 ./...
	# Windows
	GOOS=windows GOARCH=amd64 go build -o bin/main-windows-amd64 ./...


all: test run
